image: nixos/latest
repositories:
  nixpkgs: https://nixos.org/channels/nixos-20.09
sources:
  - https://git.sr.ht/~matthiasbeyer/prometheus-mpd-exporter
tasks:
  - install: |
      cd prometheus-mpd-exporter
      nix-shell ./shell.nix --run "echo nix-shell ready"
  - build: |
      cd prometheus-mpd-exporter
      nix-shell ./shell.nix --run "echo nix-shell ready"
      nix-shell ./shell.nix --run "cargo build --all --all-features"
triggers:
  - action: email
    condition: always
    to: mail@beyermatthias.de

